matches:
- trigger: ":bloom"
  replace: "https://make.wordpress.org/training/handbook/guidelines/blooms-taxonomy/"

- trigger: ":lwp"
  replace: "https://learn.wordpress.org/"

- trigger: ":mt"
  replace: "https://make.wordpress.org/training/"

- trigger: ":gl"
  replace: "https://github.com/WordPress/learn/"

- trigger: ":gbdlp"
  replace: "https://github.com/WordPress/Learn/issues/1984"

- trigger: ":gtdlp"
  replace: "https://github.com/WordPress/Learn/issues/2045"

- trigger: ":gpdlp"
  replace: "https://github.com/WordPress/Learn/issues/2044"

- trigger: ":gadlp"
  replace: "https://github.com/WordPress/Learn/issues/2344"

- trigger: ":bdlp"
  replace: "https://learn.wordpress.org/course/beginner-wordpress-developer/"


- trigger: ":eng"
  replace: "English"

- trigger: ":cdt"
  replace: "# Details\n
              \n
              - Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson\n
              - Content title: \n
              - Topic description: \n
              - Audience (User, Developer, Designer, Contributor, etc.): Developer\n
              - Experience Level (Beginner, Intermediate, Advanced, Any): \n
              \n
              # Learning Objectives\n
              <!--\n
              What will the learner be able to do as a result of this content?\n
              -->\n
              \n
              # Related Resources and Other Notes\n
              \n
              ### Automation Code\n
              <!-- \n
              Under this comment, type two slashes (//) followed by the code that represents the content type. (Like //example) \n
              - Online Workshop = online-workshop\n
              - Lesson = lesson\n
              - Course = course\n
              - Tutorial = tutorial\n
              - Lesson Plan = teach\n
              Once submitted, that code will add a new comment to the issue with the relevant development checklist.\n
              -->\n
              //lesson"

- trigger: ":ipl"
  replace: "# Details\n
              \n
              - Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson\n
              - Content title: \n
              - Topic description: \n
              - Audience (User, Developer, Designer, Contributor, etc.): Developer\n
              - Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate\n
              \n
              # Prerequisites\n
              <!--\n
              What lessons on learn.wordpress.org should the learner have already completed?\n
              -->\n
              \n
              It is assumed that the learner has already completed the following lessons:\n
               - [Beginner WordPress developer](https://learn.wordpress.org/course/beginner-wordpress-developer/)\n
                - Modules 1 - 8\n
              \n
              # Learning Objectives\n
              <!--\n
              What will the learner be able to do as a result of this content?\n
              -->\n
              \n
              # Related Resources and Other Notes\n
              \n
              ### Automation Code\n
              <!-- \n
              Under this comment, type two slashes (//) followed by the code that represents the content type. (Like //example) \n
              - Online Workshop = online-workshop\n
              - Lesson = lesson\n
              - Course = course\n
              - Tutorial = tutorial\n
              - Lesson Plan = teach\n
              Once submitted, that code will add a new comment to the issue with the relevant development checklist.\n
              -->\n
              //lesson"

- trigger: ":ow"
  replace: "## Online Workshop Details\n
          - Date:\n
          - Meetup.com event link:\n
          - Co-host: \n
          \n
          ## Online Workshop Development Checklist\n
          - [ ] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)\n
          - [ ] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)\n
          - [ ] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the \"Needs Co-host\" tag from issue once assigned)\n
          - [ ] Hold Online Workshop\n
          - [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps\n
          - [ ] Add link to slides and/or WordPress.tv video to GitHub issue"

- trigger: ":ytd"
  replace: "View this lesson and others in this course at Learn WordPress:\n"

- trigger: ":wpd"
  replace: "WordPress Developer"

- trigger: "cci"
  replace: "Hi :wave:\n
\n
I'm reaching out because you applied to take part in the next Learn WordPress course cohort: https://make.wordpress.org/training/2024/10/13/announcing-the-next-learn-wordpress-course-cohort/\n
\n
I'm pleased to let you know that your cohort facilitators (@Lax Mariappan and myself) are accepting all valid applications this time round. We'll have 39 participants taking part in this cohort, the largest we've ever tackled.\n
\n
The cohort officially starts next week, so I would like to confirm that you're still interested in taking part. I would also like to confirm that you're available to join the weekly calls, which are happening every Wednesday at 12:00 UTC for the duration of the cohort.\n
\n
If you are still interested and available for the weekly calls, please let me know, and I'll add you to the cohort Slack channel to get started.\n
"
